/* WordSplit — morpheme database
 * Each entry: "forms|meaning|origin|examples"
 *   forms    comma-separated spellings that map to the same morpheme
 *   meaning  short gloss shown in the split view
 *   origin   L = Latin, G = Greek, OE = Old English, F = French, other
 *   examples comma-separated sample words
 */

const PREFIXES = [
  "a,an|not, without|G|atypical,anarchy,amoral",
  "ab,abs|away from, off|L|abduct,abstain,abnormal",
  "ac,ad,af,ag,al,ap,ar,as,at|to, toward, near|L|adhere,affix,aggregate,attract",
  "ambi,amphi|both, around|L/G|ambidextrous,ambiguous,amphibian",
  "ana|up, back, again|G|analysis,anachronism,anatomy",
  "ante|before, in front of|L|antecedent,antebellum,anterior",
  "anti,ant|against, opposite|G|antidote,antipathy,antagonist",
  "apo|away from, separate|G|apology,apostasy,apogee",
  "auto|self|G|autonomy,automatic,autobiography",
  "caco|bad, harsh|G|cacophony,cacography",
  "be|thoroughly, make|OE|bedeck,bewilder,belittle",
  "bene,bon|good, well|L|benefit,benevolent,bonus",
  "bi,bin|two, twice|L|bilingual,bisect,binary",
  "cata|down, completely|G|catastrophe,catalog,cataract",
  "circum|around|L|circumvent,circumference,circumspect",
  "co,col,com,con,cor|with, together|L|cooperate,collaborate,convene,correlate",
  "contra,counter|against, opposite|L|contradict,contravene,counteract",
  "de|down, away, remove|L|descend,deduct,defame",
  "deca|ten|G|decade,decathlon,decagon",
  "demi|half|F|demigod,demitasse",
  "di|two, double|G|dioxide,dilemma,dichotomy",
  "dia|through, across|G|diameter,dialogue,diagnose",
  "dif,dis|not, apart, away|L|disperse,dissent,differ",
  "dys|bad, difficult|G|dysfunction,dyslexia,dystopia",
  "e,ef,ex|out, out of, former|L|eject,exhale,efface,exclude",
  "ecto|outside|G|ectoderm,ectoplasm",
  "en,em|in, into, cause to be|L/F|enclose,embrace,empower",
  "endo|within|G|endoskeleton,endogenous",
  "epi|upon, over, after|G|epidemic,epitaph,epilogue",
  "equi|equal|L|equidistant,equilibrium,equivocate",
  "eu|good, well, pleasant|G|euphony,eulogy,euphemism",
  "extra,extro|beyond, outside|L|extraordinary,extrovert,extraneous",
  "fore|before, in front|OE|foresee,forecast,foreboding",
  "geo|earth|G|geography,geology,geothermal",
  "hemi|half|G|hemisphere,hemiplegia",
  "hetero|different, other|G|heterogeneous,heterodox",
  "homo,homeo|same, alike|G|homogeneous,homonym,homeostasis",
  "hyper|over, excessive, above|G|hyperbole,hyperactive,hypertension",
  "hypo|under, below, too little|G|hypothesis,hypocrite,hypodermic",
  "il,im,in,ir|not, without|L|illegal,immature,inept,irregular",
  "im,in|in, into, onto|L|immerse,influx,incision",
  "infra|below, beneath|L|infrastructure,infrared",
  "inter|between, among|L|intervene,interrupt,intersperse",
  "intra,intro|within, inside|L|intramural,introspect,introvert",
  "iso|equal|G|isolate,isosceles,isotope",
  "juxta|next to|L|juxtapose",
  "macro|large, long|G|macrocosm,macroeconomics",
  "mal,male|bad, evil, wrong|L|malice,malign,malfunction",
  "meta|change, beyond, after|G|metamorphosis,metaphor,metaphysics",
  "micro|small|G|microscope,microcosm,microbe",
  "mid|middle|OE|midway,midterm",
  "milli|thousand, thousandth|L|millennium,millimeter",
  "mis|wrong, badly, hate|OE/L|mislead,misanthrope,misconstrue",
  "mono|one, single|G|monotony,monarch,monolith",
  "multi|many|L|multitude,multiply,multifarious",
  "neo|new, recent|G|neologism,neophyte,neonatal",
  "non|not|L|nonentity,nonchalant,nonpareil",
  "ob,oc,of,op|against, toward, in the way|L|obstruct,occlude,oppose,offend",
  "octo,oct|eight|L/G|octagon,octave,October",
  "omni|all, every|L|omnipotent,omnivorous,omniscient",
  "ortho|straight, correct|G|orthodox,orthography,orthopedic",
  "out|beyond, surpassing|OE|outlast,outmoded,outstrip",
  "over|above, too much|OE|overwhelm,overt,overbearing",
  "pan|all, every|G|panacea,pandemic,panorama",
  "para|beside, beyond, resembling|G|parallel,paradox,paragon",
  "penta|five|G|pentagon,pentathlon",
  "per|through, thoroughly|L|persist,pervade,perennial",
  "peri|around, near|G|perimeter,periscope,peripheral",
  "philo,phil|loving|G|philosophy,philanthropy,philology",
  "poly|many|G|polygon,polyglot,polemic",
  "post|after, behind|L|postpone,posterity,posthumous",
  "pre|before, in front of|L|predict,preclude,premonition",
  "pro|forward, before, in favor of|L|propel,proponent,prologue",
  "proto|first, earliest|G|prototype,protagonist,protocol",
  "pseudo|false|G|pseudonym,pseudoscience",
  "quadr,quart|four|L|quadrant,quadruple,quarter",
  "quint|five|L|quintet,quintessence",
  "re|again, back|L|revive,recur,retract",
  "retro|backward, behind|L|retrospect,retrograde,retroactive",
  "se|apart, aside|L|secede,segregate,seclude",
  "semi|half, partly|L|semicircle,semiconscious",
  "sub,suc,suf,sug,sup,sus|under, below, secretly|L|submerge,succumb,suppress,sustain",
  "super,sur|above, over, beyond|L|superior,surpass,supersede",
  "syl,sym,syn,sys|together, with|G|symphony,synthesis,syllable,system",
  "tele|far, distant|G|telescope,telepathy,telegraph",
  "trans,tra|across, beyond, through|L|transmit,traverse,transcend",
  "tri|three|L/G|triangle,trivial,triumvirate",
  "ultra|beyond, extremely|L|ultraviolet,ultramodern",
  "un|not, opposite of|OE|unable,unravel,unwitting",
  "under|beneath, too little|OE|undermine,understate",
  "uni|one|L|unify,unanimous,unilateral",
  "vice|in place of|L|viceroy,vice-president",
  "with|against, back|OE|withstand,withhold,withdraw"
];

const ROOTS = [
  "acr,acer,acu|sharp, bitter|L|acrid,acute,acerbic,exacerbate",
  "act,ag|to do, to drive|L|action,agent,agile,agenda",
  "ali,alter|other, another|L|alias,alienate,altruism,alternative",
  "alt|high, deep|L|altitude,exalt,altimeter",
  "am,amor|love|L|amiable,amorous,enamored,amity",
  "anim|mind, life, spirit|L|animate,unanimous,magnanimous,animosity",
  "ann,enn|year|L|annual,perennial,annals,millennium",
  "anthrop|human being|G|anthropology,misanthrope,philanthropy",
  "apt,ept|fit, suitable|L|adapt,aptitude,inept,adept",
  "aqu|water|L|aquatic,aquarium,aqueduct",
  "arch|chief, ruler, first|G|monarch,architect,archaic,anarchy",
  "aud,audit|to hear|L|audience,audible,auditorium,audition",
  "aug,auct|to increase|L|augment,auction,august",
  "bell,belli|war|L|rebel,belligerent,antebellum,bellicose",
  "bibl|book|G|bibliography,Bible,bibliophile",
  "bio|life|G|biology,biography,symbiosis,biopsy",
  "brev|short|L|brief,abbreviate,brevity",
  "cad,cas,cid|to fall, to happen|L|cascade,accident,incident,decadent",
  "cand|to glow, white|L|candid,candle,incandescent",
  "cap,capt,cept,cip|to take, to seize|L|capture,accept,recipient,incipient",
  "capit,cipit|head|L|capital,decapitate,precipitate",
  "carn|flesh|L|carnivore,incarnate,carnage",
  "ced,cess,ceed|to go, to yield|L|precede,recession,concede,proceed",
  "cent|hundred|L|century,percent,centennial",
  "cern,cret,crim,crit|to separate, to judge|L/G|discern,secret,discriminate,critic",
  "chron|time|G|chronic,synchronize,anachronism,chronology",
  "cide,cis|to cut, to kill|L|incision,homicide,concise,decide",
  "cit|to call, to arouse|L|cite,incite,recite,solicit",
  "civ|citizen|L|civic,civilian,civility",
  "claim,clam|to shout, to cry out|L|exclaim,clamor,proclaim,acclaim",
  "clar|clear|L|clarify,declare,clarity",
  "clin|to lean, to bend|L|incline,recline,proclivity",
  "clud,clus,clos|to shut, to close|L|exclude,seclusion,closure,recluse",
  "cogn,gnos|to know|L/G|recognize,cognition,diagnose,agnostic",
  "cord,cour|heart|L|accord,cordial,courage,discord",
  "corp|body|L|corporation,corpse,incorporate,corpulent",
  "cosm|universe, order|G|cosmos,cosmic,microcosm,cosmopolitan",
  "crat,cracy|rule, power|G|democracy,autocrat,bureaucracy",
  "cre,cresc,cret|to grow|L|create,increase,crescent,accretion",
  "cred|to believe, to trust|L|credit,incredible,credulous,creed",
  "cul,colon|to till, to inhabit|L|agriculture,colony,cultivate",
  "culp|blame, fault|L|culprit,culpable,exculpate",
  "cur,curr,curs|to run, to flow|L|current,recur,cursory,excursion",
  "cura|care|L|curator,accurate,procure,sinecure",
  "dem|people|G|democracy,epidemic,demagogue,endemic",
  "dic,dict|to say, to speak|L|dictate,predict,contradict,indict",
  "doc,doct|to teach|L|doctrine,document,indoctrinate,docile",
  "dol|to grieve, pain|L|condolence,doleful,indolent",
  "domin|master, lord|L|dominate,dominion,indomitable",
  "don,dot,dow|to give|L|donate,donor,antidote,endow",
  "dorm|to sleep|L|dormant,dormitory,dormer",
  "dox,dog|opinion, belief, teaching|G|orthodox,paradox,dogma,dogmatic",
  "duc,duct|to lead|L|conduct,induce,abduct,ductile",
  "dur|hard, lasting|L|durable,endure,obdurate,duress",
  "dyn|power|G|dynamic,dynasty,dynamite",
  "ego|self|L|egotist,egocentric,alter ego",
  "equ|equal, fair|L|equity,equanimity,equivalent,iniquity",
  "err|to wander, to stray|L|error,erratic,errant,aberration",
  "ev|age, time|L|medieval,longevity,coeval",
  "fac,fact,fect,fic|to make, to do|L|factory,affect,efficient,artifice",
  "fal,fals,fail|to deceive|L|false,fallacy,infallible,default",
  "fer|to carry, to bear|L|transfer,refer,fertile,vociferous",
  "fid|faith, trust|L|confide,fidelity,perfidy,diffident",
  "fin|end, limit|L|final,infinite,definitive,affinity",
  "firm|strong, steady|L|confirm,affirm,infirm,firmament",
  "flect,flex|to bend|L|reflect,flexible,inflection,deflect",
  "flict|to strike|L|conflict,inflict,afflict",
  "flu,fluct,flux|to flow|L|fluent,influence,fluctuate,superfluous",
  "form|shape|L|conform,reform,formative,multiform",
  "fort|strong|L|fortify,fortitude,effort,forte",
  "frag,fract|to break|L|fragment,fracture,infraction,refract",
  "fug|to flee|L|refuge,fugitive,centrifugal,subterfuge",
  "fund,found,fus|to pour, to melt, base|L|refund,profuse,foundation,infuse",
  "gen|birth, kind, race|L/G|genesis,generate,congenital,indigenous",
  "grad,gress|to step, to go|L|gradual,progress,digress,transgress",
  "gram,graph|to write, to draw|G|telegram,autograph,graphic,epigram",
  "grat|pleasing, thankful|L|gratitude,gracious,ingratiate,gratuitous",
  "grav,griev|heavy, serious|L|gravity,grievance,aggravate,grave",
  "greg|flock, herd|L|congregate,gregarious,egregious,segregate",
  "hab,hib|to have, to hold|L|habit,inhabit,prohibit,habitual",
  "helio|sun|G|heliocentric,heliotrope",
  "her,hes|to stick|L|adhere,cohesion,inherent,hesitate",
  "hydr|water|G|hydrate,dehydrate,hydraulic",
  "ject|to throw|L|reject,project,conjecture,trajectory",
  "jud,jur,jus|law, justice, to swear|L|judicial,perjury,justify,jurisdiction",
  "junct,join|to join|L|junction,conjunction,adjoin,juncture",
  "lab,labor|work|L|laborious,elaborate,collaborate",
  "lat|to carry, side|L|relate,translate,dilate,collateral",
  "lav,lut,luv|to wash|L|lavatory,dilute,deluge,ablution",
  "lect,leg,lig|to choose, to read, to gather|L|collect,legible,eligible,elect",
  "lev|to lift, light|L|elevate,alleviate,levity,relevant",
  "liber|free|L|liberty,liberal,deliverance,libertine",
  "lith|stone|G|monolith,lithograph,neolithic",
  "loc,loqu,locut|to speak|L|eloquent,soliloquy,elocution,loquacious",
  "log,logu|word, study, reason|G|logic,dialogue,monologue,neologism",
  "luc,lum,lus|light|L|lucid,illuminate,translucent,luster",
  "lud,lus|to play|L|elude,illusion,allude,ludicrous",
  "magn|great, large|L|magnify,magnitude,magnanimous,magnate",
  "man,manu|hand|L|manual,manipulate,emancipate,manuscript",
  "mand,mend|to order, to entrust|L|command,mandate,recommend,remand",
  "mar|sea|L|marine,maritime,submarine",
  "mater,matr|mother|L|maternal,matriarch,matrimony",
  "med,medi|middle|L|median,mediate,intermediate,mediocre",
  "mem,mne|to remember|L/G|memory,commemorate,amnesia,mnemonic",
  "ment,mens|mind|L|mental,demented,reminisce,commensurate",
  "merg,mers|to dip, to plunge|L|submerge,immerse,emerge,merger",
  "meter,metr|measure|G|thermometer,symmetry,geometry,metric",
  "migr|to move, to wander|L|migrate,immigrant,emigrate",
  "min|small, less|L|minute,diminish,minimal,minutiae",
  "mit,miss|to send|L|transmit,mission,remit,emissary",
  "mob,mot,mov|to move|L|mobile,motive,promote,remove",
  "mon,monit|to warn, to advise|L|monitor,admonish,premonition,monument",
  "mor,mort|death|L|mortal,mortify,moribund,immortal",
  "morph|shape, form|G|metamorphosis,amorphous,morphology",
  "mut|to change|L|mutate,immutable,commute,permutation",
  "nasc,nat|to be born|L|native,innate,nascent,renaissance",
  "nav|ship|L|navigate,naval,circumnavigate",
  "nec,noc,nox|harm, death|L|innocuous,noxious,pernicious,internecine",
  "nom,nym,onym|name|G/L|nominate,synonym,anonymous,misnomer",
  "nom,nomy|law, order, system|G|autonomy,economy,astronomy,taxonomy",
  "nov|new|L|novel,innovate,renovate,novice",
  "nounc,nunci|to declare|L|announce,denounce,renounce,enunciate",
  "numer|number|L|numerous,enumerate,innumerable",
  "onus,oner|burden|L|onerous,exonerate,onus",
  "oper|to work|L|operate,cooperate,opus",
  "pac,pas,peas|peace|L|pacify,pacifist,appease,pact",
  "par|equal|L|par,disparate,parity,compare",
  "pare,par|to prepare, to get|L|prepare,repair,apparatus,pare",
  "pat,pass,path|to feel, to suffer|L/G|patient,passion,empathy,apathy",
  "pater,patr|father, country|L|paternal,patriot,patronize,expatriate",
  "ped,pod|foot|L/G|pedal,pedestrian,impede,tripod",
  "ped|child, education|G|pediatrics,pedagogy,encyclopedia",
  "pel,puls|to drive, to push|L|propel,compel,repulse,impulsive",
  "pend,pens|to hang, to weigh, to pay|L|pendant,suspend,pensive,compensate",
  "pet,peat|to seek, to strive|L|petition,compete,repeat,impetus",
  "phan,phen,fant|to show, to appear|G|phantom,phenomenon,fantasy,epiphany",
  "phil|love|G|philosophy,bibliophile,philanthropy",
  "phob|fear|G|phobia,claustrophobia,xenophobia",
  "phon|sound, voice|G|telephone,symphony,euphony,cacophony",
  "phot|light|G|photograph,photosynthesis",
  "plac|to please, to calm|L|placid,placate,complacent,implacable",
  "pleb,popul,publ|people|L|plebeian,population,public,republic",
  "plen,plet|to fill, full|L|plenty,replete,deplete,plenary",
  "plic,ply,plex|to fold, to weave|L|complicate,imply,perplex,duplicity",
  "pon,pos,post|to place, to put|L|component,deposit,posture,juxtapose",
  "port|to carry|L|transport,portable,deport,comport",
  "pot|power|L|potent,potential,despot,impotent",
  "prehend,pris|to seize, to grasp|L|comprehend,apprehend,reprisal,comprise",
  "prim,prin|first|L|primary,primitive,principal,primeval",
  "priv|separate, individual|L|private,deprive,privation",
  "prob,prov|to test, to prove, good|L|probe,approve,reprobate,probity",
  "propri|one's own|L|property,appropriate,proprietary",
  "punct,pung|point, to prick|L|puncture,punctual,pungent,expunge",
  "pur|pure|L|purify,purge,expurgate",
  "put|to think, to prune|L|compute,dispute,reputation,impute",
  "quer,quir,quis,ques|to ask, to seek|L|inquiry,acquire,inquisitive,query",
  "quie,quit|rest, quiet|L|quiet,acquiesce,tranquil,requiem",
  "rect,reg|straight, to rule|L|correct,rectify,regulate,regime",
  "rid,ris|to laugh|L|ridicule,derision,risible",
  "rog|to ask|L|interrogate,arrogant,abrogate,derogatory",
  "rupt|to break|L|erupt,interrupt,rupture,corrupt",
  "sacr,sanct,secr|holy|L|sacred,sanctuary,consecrate,sacrilege",
  "sal,sil,sult,saul|to leap|L|assail,resilient,exult,insult",
  "sat,satis|enough|L|satisfy,saturate,satiate,insatiable",
  "sci|to know|L|science,conscious,omniscient,prescient",
  "scop|to see, to examine|G|microscope,scope,telescopic",
  "scrib,script|to write|L|describe,manuscript,inscribe,proscribe",
  "sec,sequ,secut|to follow|L|sequence,consecutive,obsequious,sequel",
  "sect,seg|to cut|L|dissect,section,segment,intersect",
  "sed,sess,sid|to sit, to settle|L|sediment,session,reside,assiduous",
  "sens,sent|to feel, to be aware|L|sensory,sentiment,consent,dissent",
  "sert|to join, to put|L|insert,assert,desert,exert",
  "serv|to save, to serve, to keep|L|preserve,servile,conserve,observant",
  "sign|mark, sign|L|signal,designate,significant,resign",
  "simil,simul|like, same|L|similar,assimilate,simulate,verisimilitude",
  "sol|alone|L|solitary,desolate,solo,soliloquy",
  "sol|sun|L|solar,solstice,parasol",
  "solv,solu,solut|to loosen, to free|L|solve,dissolve,absolve,resolution",
  "somn|sleep|L|insomnia,somnolent,somnambulist",
  "son|sound|L|sonic,resonate,dissonance,sonorous",
  "soph|wisdom|G|philosophy,sophomore,sophisticated,sophistry",
  "spec,spic,spect|to look, to see|L|inspect,conspicuous,perspective,circumspect",
  "sper|hope|L|desperate,prosperous,despair",
  "spers,sparse|to scatter|L|disperse,intersperse,sparse",
  "spir|to breathe|L|inspire,aspire,respiration,dispirited",
  "st,sta,stat,sist|to stand, to set|L|stable,status,persist,obstinate",
  "strain,strict,string|to bind, to draw tight|L|restrain,constrict,stringent,astringent",
  "stru,struct|to build|L|construct,instruct,obstruct,construe",
  "sum,sumpt|to take, to use up|L|assume,consume,presumption,resume",
  "tac,tic|silent|L|tacit,taciturn,reticent",
  "tang,tact,tig,ting|to touch|L|tangible,contact,contiguous,contingent",
  "tempor|time|L|temporary,contemporary,extemporaneous,temporal",
  "ten,tain,tent,tin|to hold, to keep|L|retain,tenacious,contents,abstinent",
  "tend,tens,tent|to stretch|L|extend,tension,contend,portent",
  "term|end, boundary|L|terminate,determine,interminable",
  "terr|earth, land|L|territory,terrestrial,subterranean,inter",
  "test|to witness|L|testify,protest,attest,testimony",
  "the,theo|god|G|theology,atheist,monotheism,apotheosis",
  "therm|heat|G|thermal,thermometer,hypothermia",
  "tom|to cut|G|atom,anatomy,dichotomy,epitome",
  "tort,tors|to twist|L|distort,contort,torsion,tortuous",
  "tract|to pull, to drag|L|attract,retract,intractable,protract",
  "trib|to pay, to give|L|tribute,contribute,attribute,tributary",
  "trud,trus|to thrust, to push|L|intrude,protrude,abstruse,obtrusive",
  "turb|to disturb, confusion|L|disturb,turbulent,perturb,turbid",
  "umbr|shadow|L|umbrella,adumbrate,penumbra,umbrage",
  "und,ound|wave, to flow|L|undulate,abundant,redundant,inundate",
  "urb|city|L|urban,suburb,urbane",
  "vac,van,void|empty|L|vacant,evacuate,vanish,vanity",
  "vad,vas|to go|L|invade,evade,pervasive,evasive",
  "val,vail|strength, worth|L|valid,prevail,valor,convalesce",
  "ven,vent|to come|L|convene,intervene,advent,circumvent",
  "ver|true|L|verify,veracity,verdict,aver",
  "verb|word|L|verbal,verbose,proverb,verbatim",
  "vers,vert|to turn|L|reverse,convert,averse,inadvertent",
  "vest|clothing|L|vest,divest,investiture,travesty",
  "via,vi|way, road|L|deviate,obviate,trivial,viaduct",
  "vict,vinc|to conquer|L|victory,convince,evict,invincible",
  "vid,vis|to see|L|evident,vision,supervise,provident",
  "viv,vit|life, to live|L|survive,vivid,vital,convivial",
  "voc,vok|to call, voice|L|vocal,advocate,revoke,equivocate",
  "vol|to wish, to will|L|volunteer,volition,benevolent,malevolent",
  "volv,volut|to roll, to turn|L|revolve,involve,convoluted,evolution",
  "vor|to eat|L|carnivore,voracious,devour,omnivorous",
  "xen|foreign, stranger|G|xenophobia,xenon",
  "zo|animal, life|G|zoology,protozoan,zodiac",
  "alg|pain|G|analgesic,neuralgia,nostalgia",
  "ang,anx|to choke, to distress|L|anguish,anxious,angst",
  "arbit|to judge|L|arbiter,arbitrary,arbitrate",
  "ard|to burn|L|ardent,ardor,arson",
  "avar,avid|eager, greedy|L|avarice,avid,avidity",
  "bil|strength, ability|L|debilitate,ability,habilitate",
  "bov|cow, ox|L|bovine,beef",
  "cart,chart|map, paper|G|cartography,chart,charter",
  "cathar|pure, clean|G|catharsis,cathartic",
  "caten|chain|L|concatenate,catenary",
  "caus,caut|to burn|G|caustic,cauterize,holocaust",
  "cav|hollow|L|cavity,concave,excavate",
  "cens|to judge, to assess|L|censure,censor,census",
  "cerebr|brain|L|cerebral,cerebrum",
  "chol|bile, anger|G|choleric,melancholy",
  "cili|to call together|L|conciliate,reconcile,council",
  "clem|mild, merciful|L|clemency,inclement",
  "clysm,clys|to wash|G|cataclysm,clyster",
  "cogit|to think|L|cogitate,excogitate",
  "cop,copi|plenty|L|copious,cornucopia",
  "crypt|hidden|G|cryptic,cryptography,apocryphal",
  "culmin|summit, top|L|culminate,culmination",
  "cupid,cup|desire, longing|L|cupidity,concupiscence",
  "curt|short|L|curtail,curt,curtailment",
  "cyn|dog|G|cynic,cynical,cynosure",
  "decor|beauty, grace, fitting|L|decorous,decorum,decorate",
  "dexter|right hand, skillful|L|dexterous,ambidextrous,dexterity",
  "dign|worthy|L|dignity,indignant,deign",
  "feder,fed|treaty, trust|L|federal,confederate,federation",
  "funct,fung|to perform|L|function,defunct,perfunctory",
  "grand|great, large|L|grandiose,aggrandize,grandeur",
  "lict,linqu|to leave|L|derelict,relinquish,delinquent",
  "line|line, thread|L|delineate,linear,lineage",
  "lys,lyt|to loosen, to break down|G|catalyst,analysis,paralysis",
  "neg|to deny|L|negate,renege,abnegate",
  "nect,nex|to bind, to tie|L|annex,connect,nexus",
  "nigr|black|L|denigrate,negritude",
  "not|to mark, to note|L|notation,connotation,denote",
  "null,nihil|nothing, none|L|nullify,annul,nihilism",
  "ori,ort|to rise, to begin|L|origin,abortive,orient",
  "phem|to speak|G|blasphemy,euphemism,prophet",
  "pict,ping|to paint|L|depict,picture,pigment",
  "plor|to cry out, to weep|L|deplore,implore,explore",
  "prav|crooked, wrong|L|depravity,deprave",
  "prec|to pray, to entreat|L|deprecate,imprecation,precarious",
  "riv|stream, bank|L|derivative,rival,riverine",
  "scend,scens,scent|to climb|L|ascend,transcend,condescend",
  "sicc|dry|L|desiccate,siccative",
  "spond,spons|to promise, to pledge|L|respond,despondent,sponsor",
  "ter,trit|to rub, to wear|L|attrition,contrite,detriment",
  "troph|nourishment|G|atrophy,hypertrophy,dystrophy",
  "vot,vow|to vow, to pledge|L|devout,devote,vow",
  "sal,sail|to leap, to rush|L|assail,salient,sally",
  "greg,grega|flock|L|gregarious,congregation",
  "flu,fluv|to flow|L|fluvial,confluence,effluent",
  "grat,grac|pleasing, thankful|L|gracious,gratify,disgrace",
  "lat,later|side, wide|L|lateral,collateral,dilate",
  "leg,legis|law|L|legal,legislate,legitimate",
  "liter|letter|L|literate,literal,alliteration",
  "mens,mensur|to measure|L|dimension,commensurate,immense",
  "milit|soldier|L|military,militant,militate",
  "mir|to wonder, to look at|L|admire,miracle,mirage",
  "ocul,op|eye|L/G|ocular,binocular,myopic",
  "orn|to decorate|L|ornate,adorn,ornament",
  "pen,pun|to punish|L|penal,penitent,impunity",
  "petr|rock, stone|G|petrify,petroleum",
  "pot,pos|able, powerful|L|potent,possible,potentate",
  "rad,ras|to scrape, to shave|L|abrasive,erase,raze",
  "radic,radix|root|L|radical,eradicate,radish",
  "sanguin|blood|L|sanguine,consanguinity",
  "sen,senec|old|L|senior,senile,senescent",
  "sever|serious, strict|L|severe,persevere,asperity",
  "simul,sembl|to resemble|L/F|assemble,resemble,dissemble",
  "tang,ting|to touch|L|tangent,contingent",
  "vac,van|empty|L|vacuous,evacuate,vanity",
  "ven,venia|forgiveness, grace|L|venial,venerate",
  "verd,vir|green, to grow|L|verdant,verdure,virescent",
  "vig,veg|lively, awake|L|vigilant,vigor,vegetate",
  "volu,volup|pleasure|L|voluptuous,volupty",
  "it,i,itin|to go|L|transient,itinerant,circuitous,initiate",
  "gn,gener|to be born, kind|L|benign,malignant,generate,congenital",
  "fut,fus|to pour, to refute|L|refute,futile,confute",
  "sag,sap|to be wise, to taste|L|sagacious,sapient,insipid,savant",
  "moll|soft|L|mollify,emollient,mollusk",
  "suav,suad|sweet, to urge|L|suave,persuade,dissuade,assuage",
  "feas,fact,feit|to do, to make|L|feasible,counterfeit,malfeasance,surfeit",
  "pugn,pugil|to fight|L|pugnacious,repugnant,impugn,pugilist",
  "surg,surrect|to rise|L|insurgent,resurrect,insurrection",
  "verg|to bend, to incline|L|converge,diverge,verge",
  "vort,vers|to turn, whirl|L|vortex,vortical",
  "rap,rapt|to seize|L|rapacious,rapture,rapt",
  "glut|to swallow|L|glutton,gluttonous,englut",
  "corrig,correct|to make straight|L|incorrigible,corrigible,correct",
  "regn,regi|to rule, kingdom|L|interregnum,reign,regime",
  "stice,stit|to stand, to stop|L|armistice,solstice,interstice",
  "forc,fort|strength|L|enforce,perforce,reinforce",
  "tenu|thin, slender|L|tenuous,attenuate,extenuate",
  "ostens,ostent|to show|L|ostensible,ostentatious,ostentation",
  "scrut|to search, to examine|L|scrutinize,inscrutable,scrutiny",
  "polit,polis|city, citizen|G|metropolis,cosmopolitan,political",
  "acro|height, tip, extreme|G|acrophobia,acropolis,acronym",
  "megal,mega|great, large|G|megalopolis,megalomania",
  "nomin,nomen|name|L|nominal,ignominious,nomenclature",
  "vag|to wander|L|vagrant,extravagant,vagary",
  "congru|to agree, to come together|L|congruent,incongruous",
  "mod,moder,commod|measure, manner, fitting|L|modicum,moderate,accommodate",
  "mun,muner,commun|duty, gift, shared|L|immunity,remuneration,communal,munificent",
  "pit,piti|to seek, to appease|L|propitiate,propitious",
  "salut,salubr|health, well-being|L|salutary,salubrious,salutation",
  "nic,noc|harm|L|pernicious,innocuous,noxious",
  "monstr|to show, to warn|L|demonstrate,remonstrate,monster",
  "mund|world, clean|L|mundane,mundanity",
  "insul|island|L|insular,insulate,peninsula",
  "flor|flower|L|florid,flourish,efflorescence",
  "flagr,flamm|to burn, to blaze|L|conflagration,flagrant,inflammatory",
  "fulg,splend|to shine|L|effulgent,refulgent,resplendent",
  "ferv|to boil, to glow|L|fervent,fervor,effervescent",
  "torp|numb, sluggish|L|torpid,torpor,torpedo",
  "langu,lass|to be faint, weary|L|languid,languish,lassitude",
  "nerv|nerve, sinew|L|enervate,innervate,nervous",
  "vigor,vig|liveliness, strength|L|invigorate,vigorous,vigor",
  "vestig|footprint, trace|L|vestige,investigate,vestigial",
  "journ,diurn|day|L|adjourn,sojourn,diurnal,journal",
  "heres,heret|to choose, to take|G|heresy,heretic,heretical",
  "schis,schiz|to split|G|schism,schizophrenia",
  "frang,fring|to break|L|frangible,infringe,refrain",
  "omin|omen, foreboding|L|ominous,abominate",
  "auspic,auspec|bird-sign, favorable omen|L|auspicious,auspice",
  "acerb,acrid|bitter, sharp|L|acerbic,exacerbate,acrid",
  "melior|better|L|ameliorate,meliorism",
  "robor,robus|strength, oak|L|corroborate,robust",
  "ubiqu|everywhere|L|ubiquitous,ubiquity",
  "sopor,somn|sleep|L|soporific,somnolent,insomnia",
  "gyn|woman|G|misogynist,gynecology",
  "icon|image, likeness|G|iconoclast,iconic,icon",
  "clast|to break|G|iconoclast,osteoclast",
  "agog|leader, to lead|G|demagogue,pedagogue,synagogue",
  "gon|angle, corner|G|polygon,paragon,pentagon",
  "dig,dic|to point, to say|L|prodigy,prodigal,indicate",
  "ambul|to walk|L|ambulatory,perambulate,somnambulist",
  "itiner|journey, route|L|itinerant,itinerary",
  "stant,stagn|to stand, standing water|L|substantiate,stagnant,circumstantial",
  "stit,stitut|to set up, to place|L|constituent,destitute,institute",
  "ascet|to exercise, to train|G|ascetic,asceticism",
  "arbor|tree|L|arboreal,arboretum",
  "ram,radic,racin|branch, root|L|ramification,eradicate,deracinate",
  "esoter|inner, within|G|esoteric,esoterica",
  "cond,condit|to hide, to found|L|recondite,abscond,condiment",
  "tus,tund|to beat, to blunt|L|obtuse,contusion",
  "quotid|daily, everyday|L|quotidian",
  "nomad|to wander for pasture|G|nomad,nomadic",
  "patet,pat|to walk, to be open|G/L|peripatetic,patent",
  "letharg|forgetfulness, idleness|G|lethargic,lethargy",
  "bull,ebull|to boil, to bubble|L|ebullient,ebullience",
  "uber|fruitful, abundant|L|exuberant,exuberance",
  "pareil,par|equal|F/L|nonpareil,apparel",
  "mount,mont|mountain, to rise|L|paramount,surmount,promontory",
  "minut,minus|small|L|minutiae,minuscule,diminution",
  "plais,plac|to please|L/F|complaisant,placate,complacent",
  "palli|cloak, to cover|L|palliate,palliative",
  "deleter|destructive|G|deleterious",
  "truc|fierce, savage|L|truculent,truculence",
  "streper|noisy|L|obstreperous",
  "calc,calcitr|to kick, heel|L|recalcitrant,inculcate",
  "pusill|very small, petty|L|pusillanimous",
  "quixot|like Don Quixote, idealistic|Sp|quixotic",
  "hemer|day|G|ephemeral,ephemera",
  "lac,laconic|of Laconia, terse|G|laconic",
  "prevaric|to walk crookedly|L|prevaricate",
  "fusc|dark, dusky|L|obfuscate,fuscous",
  "sine|without|L|sinecure",
  "rept,rep|to creep|L|surreptitious,reptile",
  "ostrac|shell, potsherd used for voting|G|ostracize,ostracism",
  "lix|liquid, to flow|L|prolix",
  "cinct|to gird, to bind|L|succinct,precinct",
  "capric|whim, goat-like leap|It|capricious,caprice",
  "reciproc|moving back and forth|L|reciprocal,reciprocity",
  "mendac,mendic|lying, begging|L|mendacious,mendicant",
  "amen|to lead, pleasant|L|amenable,amenity",
  "sedul|diligent, without guile|L|sedulous,sedulity",
  "fatu,vap|foolish, flat|L|fatuous,vapid,infatuated",
  "rud|rough, unlearned|L|erudite,rudimentary,rude",
  "ecumen|the inhabited world|G|ecumenical",
  "paroch,provinc|parish, province|L|parochial,provincial",
  "nown,not|to know, to name|L|renown,notable",
  "alesc,ol|to grow up|L|coalesce,adolescent",
  "zeal|ardor, fervor|G|zealous,zealot",
  "bod|to announce, to foretell|OE|foreboding,bode",
  "aprop|to the purpose|F|malapropism,apropos",
  "raign,ration|to reckon, to reason|L|arraign,rational,ratiocinate",
  "ger,gest|to carry, to wage|L|belligerent,gesture,digest",
  "cose,cosus|full of|L|bellicose,jocose",
  "relat,later|to carry, to refer|L|correlative,relate",
  "vour,vor|to devour|L|devour,voracious",
  "usurp|to seize by use|L|usurp,usurpation",
  "forest,silv|woods|L|deforest,sylvan",
  "cant,cent|to sing, hundred|L|cantilever,incantation",
  "tranquil|calm, quiet|L|tranquil,tranquility",
  "pi,pie|dutiful, devout|L|expiate,piety,pious",
  "long|long|L|longevity,elongate,prolong",
  "noctur,noct|night|L|nocturnal,nocturne,equinox",
  "part,parti|part, share|L|participate,partisan,partial",
  "flig,flict|to strike|L|profligate,conflict,afflict",
  "cosmo,cosm|universe, world, order|G|cosmopolitan,cosmos,microcosm",
  "astro,aster|star|G|astronomy,asteroid,disaster",
  "gastro,gastr|stomach|G|gastronomy,gastric",
  "taxo,tax|arrangement, order|G|taxonomy,syntax",
  "eco,oik|house, environment|G|economy,ecology",
  "herb|plant, grass|L|herbivorous,herbal",
  "arm|weapon, to equip|L|armistice,armament,disarm",
  "sap,sip,sav|taste, wisdom|L|insipid,savant,sapient"
];

const SUFFIXES = [
  "able,ible|able to be, capable of|L|readable,edible,tenable",
  "acious,cious,ious|full of, having|L|voracious,gracious,ambitious",
  "acity,icity|quality of|L|tenacity,veracity,simplicity",
  "acy,cy|state or quality of|L|privacy,accuracy,fallacy",
  "ade|action or product of|F|blockade,tirade,cascade",
  "age|action, state, or result|F|shrinkage,pilgrimage,mirage",
  "al,ial,eal|relating to|L|natural,editorial,corporeal",
  "ium,um|thing, place (noun ending)|L|compendium,podium,forum",
  "us|thing (Latin noun ending)|L|animus,census,consensus",
  "olent,ulent|full of|L|somnolent,fraudulent,corpulent",
  "ist,istic|characteristic of|G|realistic,artistic,simplistic",
  "ance|state or action of|L|abeyance,resonance,defiance",
  "al|act or process of|L|refusal,rebuttal,perusal",
  "an,ian|one who, relating to|L|comedian,American,artisan",
  "ance,ancy,ence,ency|state or quality of|L|abundance,clemency,prudence",
  "ant,ent|one who, being|L|servant,student,belligerent",
  "ar,ary|relating to, one who|L|circular,secretary,exemplary",
  "ard,art|one who does (often badly)|F|drunkard,braggart,dullard",
  "ate|to make, having|L|activate,fortunate,obdurate",
  "ation,ition,tion,ion|act or state of|L|creation,ambition,tension",
  "cle,cule,ule|small|L|particle,molecule,globule",
  "craft|skill, art|OE|witchcraft,statecraft",
  "cracy|rule, government|G|democracy,aristocracy,plutocracy",
  "crat|ruler, supporter of rule|G|autocrat,bureaucrat",
  "dom|state, domain, condition|OE|freedom,kingdom,boredom",
  "ee|one who receives|F|employee,nominee,devotee",
  "eer,ier|one concerned with|F|engineer,financier,profiteer",
  "en|made of, to make|OE|wooden,harden,enlighten",
  "er,or,ar|one who, that which|OE/L|teacher,inventor,liar",
  "ery,ry|place of, practice of|F|bakery,bravery,mimicry",
  "esce,escent|beginning to be|L|coalesce,convalescent,obsolescent",
  "ese|native of, style of|F|Chinese,journalese",
  "esque|in the style of|F|picturesque,grotesque,statuesque",
  "ess|female (older usage)|F|actress,heiress",
  "et,ette|small|F|islet,cigarette,statuette",
  "fic|making, causing|L|terrific,soporific,prolific",
  "ful|full of|OE|hopeful,artful,baleful",
  "fy,ify|to make, to cause|L|clarify,magnify,mollify",
  "gram|written record|G|telegram,diagram,epigram",
  "graph,graphy|writing, drawing|G|photograph,calligraphy,biography",
  "hood|state, condition|OE|childhood,likelihood",
  "ic,ical|relating to, like|G/L|heroic,comical,laconic",
  "ide|chemical compound|L|oxide,chloride",
  "ile|tending to, capable of|L|fragile,docile,volatile",
  "ine|relating to, made of|L|feminine,marine,saturnine",
  "ish|somewhat, like|OE|childish,greenish,squeamish",
  "ism|doctrine, belief, practice|G|heroism,skepticism,truism",
  "ist|one who practices|G|artist,pacifist,polemicist",
  "ite|native of, follower of|G|Israelite,erudite,composite",
  "itis|inflammation|G|arthritis,tonsillitis",
  "ity,ty|state or quality of|L|clarity,brevity,levity",
  "ive,ative,itive|tending to, having the nature of|L|creative,pensive,furtive",
  "ize,ise|to make, to become|G|realize,ostracize,eulogize",
  "less|without|OE|hopeless,relentless,ceaseless",
  "let|small|F|booklet,rivulet,streamlet",
  "like|resembling|OE|childlike,lifelike",
  "ling|small, minor|OE|duckling,underling,fledgling",
  "logy,ology|study of, science of|G|biology,geology,tautology",
  "ly|in the manner of, like|OE|quickly,scholarly,comely",
  "ment|act, state, or result of|L|judgment,predicament,embellishment",
  "meter,metry|measure|G|barometer,symmetry,geometry",
  "ness|state or quality of|OE|kindness,heaviness,wilderness",
  "nomy|law, system of|G|astronomy,taxonomy,economy",
  "oid|resembling|G|humanoid,asteroid,celluloid",
  "ory,orium|place for, relating to|L|laboratory,auditorium,illusory",
  "ose,ous|full of, having|L|verbose,porous,onerous",
  "phile,philia|lover of|G|bibliophile,Anglophile",
  "phobia,phobe|fear of|G|claustrophobia,technophobe",
  "phone,phony|sound|G|telephone,euphony,cacophony",
  "scope,scopy|instrument for viewing|G|microscope,periscope",
  "ship|state, skill, office|OE|friendship,craftsmanship",
  "some|characterized by|OE|troublesome,winsome,loathsome",
  "tude|state or quality of|L|solitude,fortitude,lassitude",
  "ular|relating to|L|circular,granular,molecular",
  "ure|act, process, result|L|failure,censure,tenure",
  "ward|in the direction of|OE|backward,untoward,wayward",
  "wise|in the manner of|OE|clockwise,likewise",
  "y|characterized by|OE|dirty,wary,paltry",
  "uous,ious,eous|full of, characterized by|L|conspicuous,ingenuous,erroneous",
  "ient,ent|being, doing|L|incipient,sentient,recipient",
  "id|in a state of|L|acrid,vapid,florid,lucid",
  "itious,atious,itous|full of, tending to|L|surreptitious,ostentatious,fortuitous",
  "ulate,ulous|tending to, full of|L|capitulate,credulous,modulate",
  "iate,uate|to make, to cause|L|substantiate,initiate,attenuate",
  "esis,osis,sis|process, condition|G|genesis,stasis,neurosis",
  "ics|body of knowledge, practice|G|eugenics,ethics,physics",
  "uity,ity|state or quality of|L|annuity,gratuity,acuity",
  "aneous,aneous|relating to|L|extemporaneous,instantaneous",
  "icle,cule|small|L|chronicle,particle,molecule",
  "ice,ise|act or state of|L|precipice,justice,service",
  "uary,ary|relating to, place for|L|obituary,estuary,library",
  "entary,ental|relating to|L|sedentary,elemental",
  "ual,ial|relating to|L|residual,perpetual",
  "iary,ary|relating to, one who|L|subsidiary,incendiary",
  "uent,ent|being, doing|L|constituent,affluent",
  "ute,ude|state of, made|L|destitute,solitude",
  "sy,cy|state or quality of|G|apostasy,democracy",
  "mony|resulting state or thing|L|acrimony,testimony,matrimony",
  "men,ment|result or means of|L|acumen,regimen,specimen",
  "fication,ification|the making of|L|ramification,edification,clarification",
  "escence,escent|process of becoming|L|efflorescence,convalescence",
  "atic,matic|relating to|G|dogmatic,schismatic,dramatic",
  "entious,ential|full of, relating to|L|conscientious,influential",
  "ane,ine|relating to|L|mundane,humane,marine",
  "nym,onym|name, word|G|acronym,synonym,pseudonym",
  "itas,itude|state or quality of|L|gravitas,fortitude",
  "ete,ate|having, made|L|obsolete,complete",
  "ution,ution|act or process of|L|diminution,evolution",
  "utive,ative|tending to|L|diminutive,talkative",
  "iae,ae|plural ending|L|minutiae,algae",
  "icum,ium|small thing, place|L|modicum,podium",
  "iously,ously,ally|in a manner that is|L|auspiciously,tenuously,diurnally",
  "ically|in a manner relating to|G|laconically,comically",
  "avit|he or she has done|L|affidavit",
  "el,le|small, diminutive|L|infidel,morsel,particle",
  "on,oon|one who, large|G/F|glutton,buffoon",
  "onous,onous|full of|L|gluttonous,harmonious",
  "ture,ure|act, process, result|L|rapture,culture,tenure",
  "atory,itory|relating to, place for|L|derogatory,ambulatory,dormitory",
  "imen,men|result or means of|L|regimen,specimen",
  "alia|things relating to|L|regalia,paraphernalia",
  "ionist,ist|one who practices|L|insurrectionist,perfectionist",
  "ibly,ably|in a manner able to be|L|ostensibly,notably",
  "ex,ix|thing, one who|L|vortex,index,matrix",
  "igo,ago|condition, state|L|vertigo,lumbago",
  "atile,ile|tending to, capable of|L|versatile,volatile",
  "iety,ety|state or quality of|L|satiety,variety",
  "ional,ionale|relating to|L|rational,rationale",
  "isan,esan|one who, belonging to|F|partisan,artisan",
  "arian|one who believes or does|L|sectarian,librarian,vegetarian",
  "aise,ase|state, condition|F|malaise,disease",
  "als,al|things relating to|L|annals,vitals",
  "ated,ate|having been made|L|superannuated,infatuated",
  "ing|the act of; ongoing|OE|foreboding,building",
  "ue,ual|relating to|L|retinue,residue"
];

function buildIndex(list, kind) {
  const out = [];
  list.forEach((line, i) => {
    const [forms, meaning, origin, examples] = line.split("|");
    const variants = forms.split(",");
    out.push({
      id: kind + i,
      kind,
      key: variants[0],
      variants,
      meaning,
      origin: origin || "",
      examples: (examples || "").split(",").filter(Boolean)
    });
  });
  return out;
}

const MORPHEMES = {
  prefix: buildIndex(PREFIXES, "prefix"),
  root: buildIndex(ROOTS, "root"),
  suffix: buildIndex(SUFFIXES, "suffix")
};

/* form -> entry lookup, longest forms first for greedy matching */
const FORM_MAP = { prefix: new Map(), root: new Map(), suffix: new Map() };
["prefix", "root", "suffix"].forEach(kind => {
  MORPHEMES[kind].forEach(entry => {
    entry.variants.forEach(v => {
      const key = v.trim();
      if (!key) return;
      if (!FORM_MAP[kind].has(key)) FORM_MAP[kind].set(key, []);
      FORM_MAP[kind].get(key).push(entry);
    });
  });
});

const SORTED_FORMS = {
  prefix: [...FORM_MAP.prefix.keys()].sort((a, b) => b.length - a.length),
  root: [...FORM_MAP.root.keys()].sort((a, b) => b.length - a.length),
  suffix: [...FORM_MAP.suffix.keys()].sort((a, b) => b.length - a.length)
};

const ORIGIN_NAMES = {
  L: "Latin",
  G: "Greek",
  OE: "Old English",
  F: "French",
  "L/G": "Latin / Greek",
  "G/L": "Greek / Latin",
  "L/F": "Latin / French",
  "OE/L": "Old English / Latin"
};

window.WS_MORPHEMES = MORPHEMES;
window.WS_FORM_MAP = FORM_MAP;
window.WS_SORTED_FORMS = SORTED_FORMS;
window.WS_ORIGIN_NAMES = ORIGIN_NAMES;
